### ISSUE TITLE
pid 0x6 crashed client

### ISSUE THREAD

**Issue by iteplenky** [FukkitX/AllahSupporter#1]
I removed all unnecessary plugins, but the error remained

![Screenshot_170](https://user-images.githubusercontent.com/42160062/107541265-25c6ad80-6bf1-11eb-982a-e718a8f52cc2.png)

**Comment by TalShitPosts** [comment]
Remove Loader and ServerServiceability

**Comment by iteplenky** [comment]
> Remove Loader and ServerServiceability

These are my plugins from which such an error cannot be

PMMP 3.16.1

**Comment by TalShitPosts** [comment]
> > Remove Loader and ServerServiceability
> 
> These are my plugins from which such an error cannot be
> 
> PMMP 3.16.1

still try removing them smh
