### ISSUE TITLE
What are you Doing ?????????!!!!!!!!

### ISSUE THREAD

**Issue by DragonfireHD** [FukkitX/AllahSupporter#2]
You insult because Islam calls, I ask you to delete that, you can't just call Allah an evil name with the explosion. I am Muslim and you are pushing Islam in the wrong direction allah uakbar is not a word for Explosion this use ISIS for the provocative statement to speak ill of islam  In the name of Islam, please delete this plugin

**Comment by WolFoxHD** [comment]
I support you I am also a Muslim

**Comment by JustTalDevelops** [comment]
Please check the Disclaimer section of the readme
