### ISSUE TITLE
Racist

### ISSUE THREAD

**Issue by xXNiceYT** [FukkitX/AllahSupporter#6]
Hey there fukkit development team, I’m just very mad how you’re plugin disrespects our Islam culture. Please take this down to I’ma have to pull the big guns and call the GitHub admin to take it down for you. Please never do this again, it really hurts my feelings and it’s really racist in many ways. Like really why would u wanna say allubark like what do u get of it. Please take it down i beg you.

Sincerely Muslim nice

**Comment by Newcoolboys** [comment]
I thought you were Asian tho...

**Comment by Newcoolboys** [comment]
So you're telling me I've been a friend with a Muslim?? Blah we no longer friends

**Comment by xXNiceYT** [comment]
Allah Hu Akbar

**Comment by JustTalDevelops** [comment]
OMG IM SO SORRY!!!!! fucking die retard

**Comment by Newcoolboys** [comment]
We arent done
